### ISSUE TITLE
decoding barfs on NAs in string arrays

### ISSUE THREAD

**Issue by gordonwoodhull** [att/rserve-js#2]
what's upsetting is that it reports: `Error: URI malformed`

huh? what URI? well, it's doing this:

``` js
        read_string_array: function(attributes, length) {
            var a = this.read_stream(length).make(Uint8Array);
            var result = [];
            var current_str = "";
            for (var i=0; i<a.length; ++i)
                if (a[i] === 0) {
                    current_str = decodeURIComponent(escape(current_str));
                    result.push(current_str);
                    current_str = "";
                } else {
                    current_str = current_str + String.fromCharCode(a[i]);
                }
            return [Rserve.Robj.string_array(result, attributes), length];
        },
```

we get the sequence of bytes `255,0` for NA, `current_str = "ÿ"`, and it can't be decoded.

my question for @s-u is: do we want URI decoding here? is Rserve URI encoding the strings?

then i suggest mapping this sequence to null.

[given that the array i'm trying decode has 4071492 bytes, this code is troublesome from a performance perspective, too, but i know how to deal with that: create arrays and join them rather than string `+=`]

**Comment by s-u** [comment]
Yes, that is a special case for 'NA' - it is encoded as a string containing just 0xff - since it can never occur in UTF8 in is unambiguous. And, yes, IMHO it should map to null (and vice versa).

**Comment by s-u** [comment]
And, no Rserve doesn't URI-encode strings - it's not necessary since it's all UTF8.

**Comment by gordonwoodhull** [comment]
Cool, should be an easy fix, and a small performance boost then.

**Comment by gordonwoodhull** [comment]
I bet there is something that depends on the URI decoding, but I'm still inclined to remove it because it's wrong.

**Comment by s-u** [comment]
Hm.. you mean this: `decodeURIComponent(escape(...))` - it doesn't decode, I think it's a JS trick to handle something that I can't recall. I have some dim recollection that JS doesn't actually have a way to read raw UTF8 bytes as UTF8 (yes, unbelievable...) and quick search confirms that:
http://stackoverflow.com/questions/17191945/conversion-between-utf-8-arraybuffer-and-string

**Comment by gordonwoodhull** [comment]
Meh, okay I'll leave that and fix the NA thing for RCloud 1.5 then.

**Comment by s-u** [comment]
I don't think it can be fixed at application level since by then you cannot distinguish the special sequence from different yet valid \u00ff ...

**Comment by gordonwoodhull** [comment]
Naw, I meant fixing it here in rserve.js where it's crashing. I guess it's a safe change but I'd deploy it to develop/1.5 RCloud.

**Comment by gordonwoodhull** [comment]
It appears this code also barfs on Western Latin ISO-8859 characters:

![image](https://cloud.githubusercontent.com/assets/1366709/9498553/671b5bac-4be8-11e5-9daa-a973cba7a24c.png)

![image](https://cloud.githubusercontent.com/assets/1366709/9498638/ca1ff442-4be8-11e5-9bfa-a9ee14819c59.png)

**Comment by s-u** [comment]
Strings must be UTF-8 encoded, so using Latin-1 encoded payload in strings is illegal (i.e., that is not a valid string).

**Comment by gordonwoodhull** [comment]
So this is a tl2010 bug?

**Comment by s-u** [comment]
No idea - you didn't say how you got that illegal payload - it has certainly nothing to do with rserve-js.

Perhaps rserve.conf in RCloud needs 

```
encoding utf8
```

? In RCloud we force UTF-8 locale, so under normal circumstances all should be well, but if you explicitly load a string in a different encoding in R it needs to be re-encoded to UTF8 and the above forces that at the edge.

**Comment by gordonwoodhull** [comment]
I meant, so is it a bug of an R library to produce such strings, or an RCloud bug? I'll try that, thanks.

**Comment by s-u** [comment]
R allows following encodings of strings: native (=same as the locale), UTF-8, Latin1 and bytes (see `?Encoding`). We don't support the last one, because the semantics of that are "no idea what this is, but it's some unknown encoding" so there is no way to convert that to a valid string - it's not intended to store binary payload. Rserve is designed to make sure that the client gets only one encoding by re-coding what else comes its way. By default it uses native encoding of the locale unless told otherwise.

So please file a separate bug with more details, because there too many pieces involved here. It could be that DBF (which is where tl2010 gets the strings from) flags strings incorrectly or Rserve somehow fails to re-code it properly. I don't even know where that string is passed / how it arrives on the JS side...

**Comment by gordonwoodhull** [comment]
Okay, I should be able to create a simple notebook that reproduces it, and file an RCloud bug. I will try the rserve.conf flag first, though.

**Comment by gordonwoodhull** [comment]
For posterity, changing rserve.conf didn't help. 

But as of ecbc096646b1870, rserve.js will report a more informative error message including the text that failed. And it converts the string encoding NA (`'\xff'`) to null.
