### ISSUE TITLE
Error running Quick Tour

### ISSUE THREAD

**Issue by longouyang** [att/rserve-js#5]
I tried following the Quick Tour directions. Everything worked up until the r.eval line:

```
r.eval('rnorm(10)', function(err,a) { if (err === null) { console.log(a) } else {console.log(err) }})
undefined
[ 'ERROR FROM R SERVER: ERR_inv_cmd 65538 67 16 [object ArrayBuffer]',
  67 ]
[ 'ERROR FROM R SERVER: ERR_inv_cmd 65538 67 16 [object ArrayBuffer]',
  67 ]
```

I'm on node 4.2, OS X 10.10, Rserve 1.7-3, and R 3.1.3

(I posted this as an issue in cscheid's repo a while ago but never got a response -- looks like that is abandoned?)

**Comment by longouyang** [comment]
(FWIW, I just tried Rserve 1.8-5 and got the same error)

**Comment by gordonwoodhull** [comment]
This repo is slightly ahead of @cscheid's, so yeah, we are probably better maintainers. Although he's still the expert. 

I don't think I've seen this error before. We use rserve.js every day in RCloud but I confess I haven't tried to use it elsewhere and haven't tried the instructions. I don't have time to try today but hopefully I can try later in the week.

**Comment by s-u** [comment]
This seems to have something to do with the nodejs version -- when running in older nodejs it works just fine. In nodejs 4.2.6 it breaks. On the Rserve side only an empty QAP packet arrives - it's all zeroes:

```
Responded with WebSockets.04+ handshake (version = 13)
connection accepted.
sending ID string.
WS_send_data: sending 4+ frame (ver 13), n = 34 / 34 (of total 32)
WS_recv_data for 16 (bp = 0)
INFO: WS_recv_data: read 38 bytes:
INFO: WS_recv_data frame type=02, len=32, more=0, mask=1 (need=6)
INFO: WS_recv_data frame has 32 bytes (of 32 frame), requested 16, returning partial frame

header read result: 16
DUMP [16]: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  |................
CMD=00000000, pars=0
WS_send_resp: sending 4+ frame (ver 13), n = 18 / 18 (of total 16)
```

So, Rserve just sends `ERR_inv_cmd` since 0 is a non-existing command.

**Comment by s-u** [comment]
So far it looks like a socket bug in the `ws` library to me. reserve-js attempts to send the correct buffer as witnessed by adding

```
           console.log("socket.send: "+new Uint8Array(lst[0]));
            socket.send(lst[0]);
```

and the corresponding output:

```
socket.send: 3,0,0,0,16,0,0,0,0,0,0,0,0,0,0,0,4,12,0,0,114,110,111,114,109,40,49,48,41,0,0,0
```

but the actual WS frame on the wire is just 32 bytes of zeroes which is plain wrong.

**Comment by s-u** [comment]
Confirmed, it's buggy `ws`, bumping to more recent version seems to work just fine:

```
diff --git a/package.json b/package.json
index 9596501..bf476f4 100644
--- a/package.json
+++ b/package.json
@@ -16,7 +16,7 @@
        "uglify-js": "2.3.6"
     },
     "dependencies": {
-       "ws": "0.4.27",
+       "ws": "1.1.0",
        "bluebird": "1.0.3",
        "underscore": "1.5.1"
     }
```

I'm not sure what it means for the dependency chain, so I'll leave it for now, but we should probably re-visit the version dependencies once in a while and update them.

**Comment by gordonwoodhull** [comment]
Thanks @s-u!

I think this is technically a `devDependency` that only affects testing, not a dependency that affects users downstream. So it should be safe to update without further thought.

**Comment by s-u** [comment]
I verified that bumping the dependency doesn't break on old nodejs, so I'll commit the fix.

**Comment by longouyang** [comment]
Awesome -- thanks!
